spring.application.name=nectardore
spring.datasource.url=jdbc:mysql://localhost:3306/nectardore_db
spring.datasource.username=root
spring.datasource.password=Kh@lilma$$ri2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true